name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Authenticate with Google Cloud and configure Docker automatically
    - name: Set up Cloud SDK and authenticate
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: practice-project-437604
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Build the Docker image with a timestamp tag
    - name: Build the Docker image
      run: |
        IMAGE_TAG="gcr.io/practice-project-437604/management-api:$(date +%s)"
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Push the Docker image to GCR
    - name: Push Docker image to GCR
      run: |
        docker push $IMAGE_TAG
