name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step 1: Authenticate to GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Step 2: Set up Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: practice-project-437604
        version: 'latest'

    # Step 3: Build the Docker image with timestamp tag
    - name: Build Docker image
      run: |
        IMAGE_TAG="gcr.io/practice-project-437604/management-api"
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Step 4: Push Docker image to GCR
    - name: Push Docker image
      run: docker push $IMAGE_TAG
